[workspace]

members = [
    "hello-world",
    "reverse-string",
    "gigasecond",
    "clock",
    "atbash-cipher",
    "anagram",
    "space-age",
    "sublist",
    "minesweeper",
    "luhn",
    "parallel-letter-frequency",
    "macros",
]
